version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 031857855591.dkr.ecr.ap-south-1.amazonaws.com)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t paytm-backend ./backend
      - docker build -t paytm-frontend ./frontend
      - docker tag paytm-backend:latest 031857855591.dkr.ecr.ap-south-1.amazonaws.com/paytm-backend:latest
      - docker tag paytm-frontend:latest 031857855591.dkr.ecr.ap-south-1.amazonaws.com/paytm-frontend:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push 031857855591.dkr.ecr.ap-south-1.amazonaws.com/paytm-backend:latest
      - docker push 031857855591.dkr.ecr.ap-south-1.amazonaws.com/paytm-frontend:latest
      - echo Writing image definitions file...
      - printf '[{"name":"paytm-container","imageUri":"%s"}]' 031857855591.dkr.ecr.ap-south-1.amazonaws.com/paytm-backend:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
