version: "3.9"

services:
  mongo:
    image: mongo:5
    container_name: paytm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0"]

  backend:
    build: ./backend
    container_name: paytm-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/paytm

  frontend:
    build: ./frontend
    container_name: paytm-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
